#include "teya/editor/Editor.h"
#include <imgui.h>
#include <imgui_internal.h>
#include <rlImGui.h>
#include <teya/core/Profile.h>
namespace teya::editor {
Editor::Editor(EditorHost&h):host_(h){} Editor::~Editor(){shutdown();}
bool Editor::initialize(){if(initialized_)return true;rlImGuiSetup(true);ImGui::GetIO().ConfigFlags|=ImGuiConfigFlags_DockingEnable;firstLayout_=ImGui::GetIO().IniFilename&&GetFileLength(ImGui::GetIO().IniFilename)<=0;initialized_=true;return true;}
void Editor::shutdown(){if(initialized_){rlImGuiShutdown();initialized_=false;}}
void Editor::menu(){if(ImGui::BeginMenuBar()){if(ImGui::BeginMenu("File")){if(ImGui::MenuItem("Exit"))host_.requestExit();ImGui::EndMenu();}if(ImGui::BeginMenu("View")){ImGui::MenuItem("Game View",nullptr,&gameView_.open);ImGui::MenuItem("Hierarchy",nullptr,&hierarchy_.open);ImGui::MenuItem("Inspector",nullptr,&inspector_.open);ImGui::MenuItem("Performance",nullptr,&performance_.open);ImGui::MenuItem("ImGui Demo Window",nullptr,&showDemo_);ImGui::EndMenu();}if(ImGui::BeginMenu("Debug")){if(ImGui::MenuItem("Play"))context_.play();if(ImGui::MenuItem("Pause"))context_.pause();if(ImGui::MenuItem("Step One Frame"))context_.step();ImGui::Separator();ImGui::MenuItem("Capture Game Input",nullptr,&context_.settings.captureGameInput);ImGui::MenuItem("Show Player Origin",nullptr,&context_.settings.showPlayerOrigin);ImGui::MenuItem("Show Colliders",nullptr,&context_.settings.showColliders);ImGui::EndMenu();}ImGui::EndMenuBar();}}
void Editor::toolbar(){const char* mode=context_.simulationMode()==SimulationMode::Playing?"Playing":context_.simulationMode()==SimulationMode::Paused?"Paused":"Step";ImGui::Text("Simulation: %s",mode);ImGui::SameLine();if(ImGui::Button("Play"))context_.play();ImGui::SameLine();if(ImGui::Button("Pause"))context_.pause();ImGui::SameLine();if(ImGui::Button("Step"))context_.step();ImGui::SameLine();ImGui::Checkbox("Fit",&context_.settings.fitGameView);}
void Editor::defaultLayout(){ImGuiID dock=ImGui::GetID("TeyaDockspace");ImGui::DockBuilderRemoveNode(dock);ImGui::DockBuilderAddNode(dock,ImGuiDockNodeFlags_DockSpace);ImGui::DockBuilderSetNodeSize(dock,ImGui::GetMainViewport()->WorkSize);ImGuiID left,right,center=dock;ImGui::DockBuilderSplitNode(center,ImGuiDir_Left,.2f,&left,&center);ImGui::DockBuilderSplitNode(center,ImGuiDir_Right,.25f,&right,&center);ImGuiID rightBottom;ImGui::DockBuilderSplitNode(right,ImGuiDir_Down,.35f,&rightBottom,&right);ImGui::DockBuilderDockWindow("Hierarchy",left);ImGui::DockBuilderDockWindow("Game View",center);ImGui::DockBuilderDockWindow("Inspector",right);ImGui::DockBuilderDockWindow("Performance",rightBottom);ImGui::DockBuilderFinish(dock);firstLayout_=false;}
void Editor::draw(){TEYA_PROFILE_ZONE_NAMED("GameEditor::draw");rlImGuiBegin();auto*v=ImGui::GetMainViewport();ImGui::SetNextWindowPos(v->WorkPos);ImGui::SetNextWindowSize(v->WorkSize);ImGui::SetNextWindowViewport(v->ID);ImGuiWindowFlags f=ImGuiWindowFlags_MenuBar|ImGuiWindowFlags_NoDocking|ImGuiWindowFlags_NoTitleBar|ImGuiWindowFlags_NoCollapse|ImGuiWindowFlags_NoResize|ImGuiWindowFlags_NoMove|ImGuiWindowFlags_NoBringToFrontOnFocus|ImGuiWindowFlags_NoNavFocus;ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding,0);ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize,0);ImGui::Begin("Teya Editor",nullptr,f);ImGui::PopStyleVar(2);menu();toolbar();ImGuiID dock=ImGui::GetID("TeyaDockspace");ImGui::DockSpace(dock);if(firstLayout_)defaultLayout();ImGui::End();hierarchy_.draw(host_,context_);gameView_.draw(host_,context_);inspector_.draw(host_,context_);performance_.draw(host_,context_);if(showDemo_)ImGui::ShowDemoWindow(&showDemo_);rlImGuiEnd();}
bool Editor::shouldUpdateGame(){return context_.consumeSimulationStep();} bool Editor::gameInputEnabled()const{auto&io=ImGui::GetIO();return EditorContext::allowsGameInput({gameView_.focused(),context_.settings.captureGameInput,io.WantCaptureKeyboard,io.WantCaptureMouse,ImGui::IsPopupOpen(nullptr,ImGuiPopupFlags_AnyPopupId),true,true,context_.simulationMode()});} EditorContext& Editor::context(){return context_;}
}
